baseURL = "https://liam-black-personal-website.netlify.app/"
title = "Liam Black's Website"
theme = "PaperMod"

# Theme configuration
[params]
env = "production"
author = "<author>"
description = "Portfolio description"
keywords = ["Blog", "Portfolio", "PaperMod"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false

[params.label]
text = "Home"
icon = "IMG_4771.PNG"
iconHeight = 24

[params.profileMode]
enabled = true
title = "Liam Black"
subtitle = "Computer Science Major, Psychology Minor"
imageUrl = "IMG_4771.PNG"
imageWidth = 150
imageHeight = 150











[[params.socialIcons]]
name = "github"
url = "https://github.com/LiamBlack3"



[[menu.main]]
identifier = "About me"
name = "About me"
url = "/About me/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20




[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 20

[[menu.main]]
identifier = "interests"
name = "Interests"
url = "/interests/"
weight = 20