baseURL = "https://liam-black-personal-website.netlify.app/"
title = "Liam Black's Website"
theme = "PaperMod"

# Theme configuration
[params]
env = "production"
author = "<author>"
description = "Portfolio description"
keywords = ["Blog", "Portfolio", "PaperMod"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false

[params.label]
text = "Home"
icon = "/profile.png"
iconHeight = 24

[params.profileMode]
enabled = true
title = "Liam Black"
subtitle = "Computer Science Major, Psychology Minor"
imageUrl = "profile.png"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "resume"
url = "/resume/"

[[params.profileMode.buttons]]
name = "Contact info"
url = ""



[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/"



[[params.socialIcons]]
name = "github"
url = "https://github.com/"



[[menu.main]]
identifier = "About me"
name = "About me"
url = "/About me/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "Tech-experience"
name = "Tech-experience"
url = "https://google.com/search?tbm=isch&q=cute%20puppies"
weight = 30
